# Generated by Django 5.2.13 on 2026-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Line total (net)"
            ),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Unit price (net)"
            ),
        ),
    ]
