# Generated by Django 4.2.11 on 2026-04-23 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company_name', models.CharField(blank=True, help_text='For B2B customers', max_length=255, verbose_name='Company name')),
                ('tax_id', models.CharField(blank=True, help_text='CIF/NIF', max_length=50, unique=True, verbose_name='Tax ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('segment', models.CharField(choices=[('b2c', 'B2C - Retail'), ('b2b', 'B2B - Business')], default='b2c', max_length=10, verbose_name='Customer segment')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Address name')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('both', 'Shipping & Billing')], default='both', max_length=20, verbose_name='Address type')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('country', models.CharField(default='Spain', max_length=100, verbose_name='Country')),
                ('is_default', models.BooleanField(default=False, help_text='Default address for new orders', verbose_name='Set as default')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
