# Generated by Django 5.2.13 on 2026-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_fiscal_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre comercial. For B2B customers",
                max_length=255,
                verbose_name="Company name",
            ),
        ),
    ]
