# Generated by Django 5.2.13 on 2026-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(
                        help_text="Debe coincidir con HUAN_INSTANCE, e.g. helvagres_demo",
                        max_length=100,
                        unique=True,
                        verbose_name="Instance ID",
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre comercial"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tagline"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="PNG o SVG recomendado. Altura óptima: 36-48 px.",
                        null=True,
                        upload_to="branding/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="ICO o PNG cuadrado, 32×32 px.",
                        null=True,
                        upload_to="branding/favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        blank=True,
                        help_text="Hex, e.g. #1a3a2a. Vacío = usa branding.json.",
                        max_length=20,
                        verbose_name="Color primario",
                    ),
                ),
                (
                    "color_primary_light",
                    models.CharField(
                        blank=True,
                        help_text="Hex, e.g. #2a5a40",
                        max_length=20,
                        verbose_name="Color primario claro",
                    ),
                ),
                (
                    "color_accent",
                    models.CharField(
                        blank=True,
                        help_text="Hex, e.g. #c8a84b",
                        max_length=20,
                        verbose_name="Color de acento",
                    ),
                ),
                (
                    "color_accent_light",
                    models.CharField(
                        blank=True,
                        help_text="Hex, e.g. #e2c97a",
                        max_length=20,
                        verbose_name="Color de acento claro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding settings",
                "verbose_name_plural": "Branding settings",
            },
        ),
    ]
